name: build-deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Build
      run: npm run build
    - name: Deploy
      uses: appleboy/scp-action@v0.0.7
      with:
        host: ${{ secrets.HOST }}
        key: ${{ secrets.PRIVATE_KEY }}
        username: stefan
        source: build/*
        target: ~/node-backend/public
#     - name: Deploy
#       uses: appleboy/ssh-action@v0.0.7
#       with:
#         host: ${{ secrets.HOST }}
#         key: ${{ secrets.PRIVATE_KEY }}
#         username: stefan
#         script: scp -r build/ stefan@personalswh.com:~/node-backend/public
  
